### ISSUE TITLE
Extension now requires OAuth token to function

### ISSUE THREAD

**Issue by DatGuy1** [swiftyspiffy/Twitch-Username-and-User-ID-Translator#2]
https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916

**Comment by swiftyspiffy** [comment]
Looking into this now.

**Comment by swiftyspiffy** [comment]
Just published version 1.6 to the Chrome Extension store with this change: https://github.com/swiftyspiffy/Twitch-Username-and-User-ID-Translator/commit/349a2c37cef97d14e359f656db8925c3f49eead9

Once you update, it should be working again.

**Comment by swiftyspiffy** [comment]
Aaaaaaand published 1.7 to Chrome Extension store that corrects typo in extension name. That change is here: https://github.com/swiftyspiffy/Twitch-Username-and-User-ID-Translator/commit/b91a9994db62e98eb7dfc9a9b1ad2e92e03c3f1b

**Comment by DatGuy1** [comment]
Works, but I'm wondering about starting to plan about using helix, considering Twitch's frequent API changes and all.

**Comment by swiftyspiffy** [comment]
Just saw this. We'll deal with this when we get there lol
