### ISSUE TITLE
Non-Latin Alphabet names

### ISSUE THREAD

**Issue by SwimmingLink** [swiftyspiffy/Twitch-Username-and-User-ID-Translator#5]
I understand that we can easily get what we need to use for this to work in the URL, but any chance of getting this to work with names using non-Latin characters? (i.e. using "熊川まる" instead of "kumakawamaru") - for clarification, these are names displayed directly on twitch without additional translation (I'm not asking for translation input)

**Comment by swiftyspiffy** [comment]
Unfortunately there's no current way to move from Display Name (which is what it's called in TwitchDev speak) to a Username or UserId. Given that the extension is using the Twitch API to translate between the two, I don't think this is currently possible :( . 

It was previously discussed here: https://discuss.dev.twitch.tv/t/lookup-user-by-display-name/37001/6
And a subsequent uservoice was opened here: https://twitch.uservoice.com/forums/310213/suggestions/44820925
